### ISSUE TITLE
Too many errors. Is there any compatible problems with latest version of Django?

### ISSUE THREAD

**Issue by birdyhuang** [dcramer/django-db-log#22]
➜  ecommerce30 python manage.py syncdb            
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/peng/.pyenv/versions/3.5.0/lib/python3.5/site-packages/djangodblog/models.py", line 141
    except Exception, exc:
                    ^
SyntaxError: invalid syntax

This is only a scratch. There are many deprecated usage. 

My django version is 1.9.4.

**Comment by dcramer** [comment]
This project has not been active for years.
